# For detailed configuration reference documentation, visit:
# https://supabase.com/docs/guides/local-development/cli/config
project_id = "stockeo_base_structure"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[api.tls]
enabled = false

[db]
port = 54322
shadow_port = 54320
# Doit correspondre à la version majeure de ta base distante
major_version = 17

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

# [db.vault]
# secret_key = "env(SECRET_VALUE)"

[db.migrations]
enabled = true
schema_paths = []

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[db.network_restrictions]
enabled = false
allowed_cidrs = ["0.0.0.0/0"]
allowed_cidrs_v6 = ["::/0"]

[realtime]
enabled = true
# ip_version = "IPv6"
# max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
# smtp_port = 54325
# pop3_port = 54326
# admin_email = "admin@email.com"
# sender_name = "Admin"

[storage]
enabled = true
file_size_limit = "50MiB"
# [storage.image_transformation]
# enabled = true
# [storage.buckets.images]
# public = false
# file_size_limit = "50MiB"
# allowed_mime_types = ["image/png", "image/jpeg"]
# objects_path = "./images"

# ---------------------------
# AUTH (Nettoyé & unifié)
# ---------------------------
[auth]
enabled = true

# 👉 Vite tourne sur 5173 en local
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://127.0.0.1:5173", "http://localhost:5173/dashboard"]

# Sessions
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

# Inscriptions & sécurité
enable_manual_linking = false
enable_signup = true
enable_anonymous_sign_ins = false

# Mots de passe
minimum_password_length = 8
password_requirements = "lower_upper_letters_digits"

# Clés (laissées vides: gérées par la plateforme distante)
signing_keys_path = ""
jwt_secret = "Ub5Nr702nzquTriFiHqOksbLaBZBNEORGAGhX6tTLqM="
anon_key = "env(SUPABASE_ANON_KEY)"
service_role_key = "env(SUPABASE_SERVICE_ROLE_KEY)"

# MFA (version unique, activée pour TOTP)
[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

# Emails (version unique)
[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_password_change = true
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 900

# Rate limiting (conserve)
[auth.rate_limit]
email_sent = 2
sms_sent = 30
anonymous_users = 30
token_refresh = 150
sign_in_sign_ups = 30
token_verifications = 30
web3 = 30

# SMS (version unique)
[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }}"
max_frequency = "5s"

# Provider SMS (ok de laisser désactivé)
[auth.sms.twilio]
enabled = false
account_sid = ""
message_service_sid = ""
auth_token = "env(SUPABASE_AUTH_SMS_TWILIO_AUTH_TOKEN)"

# ---------------------------
# Providers externes (inchangés)
# ---------------------------
[auth.external.apple]
enabled = false
client_id = ""
secret = "env(SUPABASE_AUTH_EXTERNAL_APPLE_SECRET)"
redirect_uri = ""
url = ""
skip_nonce_check = false

[auth.web3.solana]
enabled = false

[auth.third_party.firebase]
enabled = false
# project_id = "my-firebase-project"

[auth.third_party.auth0]
enabled = false
# tenant = "my-auth0-tenant"
# tenant_region = "us"

[auth.third_party.aws_cognito]
enabled = false
# user_pool_id = "my-user-pool-id"
# user_pool_region = "us-east-1"

[auth.third_party.clerk]
enabled = false
# domain = "example.clerk.accounts.dev"

[edge_runtime]
enabled = true
policy = "oneshot"
inspector_port = 8083
deno_version = 1
# [edge_runtime.secrets]
# secret_key = "env(SECRET_VALUE)"

[analytics]
enabled = true
port = 54327
backend = "postgres"

[experimental]
orioledb_version = ""
s3_host = "env(S3_HOST)"
s3_region = "env(S3_REGION)"
s3_access_key = "env(S3_ACCESS_KEY)"
s3_secret_key = "env(S3_SECRET_KEY)"
